# Dependabot configuration file
# Created: 2025-06-11
# Author: Nikhil-Kadapala

version: 2
updates:
  # Enable updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
<<<<<<< HEAD
      timezone: "Etc/UTC"
=======
      timezone: "UTC"
>>>>>>> eff356f9b27adefa7f33d8785f960c0810be6870
    open-pull-requests-limit: 10
    assignees:
      - "Nikhil-Kadapala"
    labels:
      - "security"
      - "dependencies"
      - "python"
    allow:
      - dependency-type: "all"
<<<<<<< HEAD
=======
        update-type: "security"
>>>>>>> eff356f9b27adefa7f33d8785f960c0810be6870
    commit-message:
      prefix: "security"
      include: "scope"

  # Enable updates for React+TypeScript dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
<<<<<<< HEAD
      interval: "daily"
      timezone: "Etc/UTC"
=======
      interval: "weekly"
      day: "monday"
>>>>>>> eff356f9b27adefa7f33d8785f960c0810be6870
    open-pull-requests-limit: 10
    assignees:
      - "Nikhil-Kadapala"
    labels:
      - "security"
      - "dependencies"
      - "frontend"
    allow:
<<<<<<< HEAD
      - dependency-type: "direct"
=======
      - dependency-type: "all"
        update-type: "security"
>>>>>>> eff356f9b27adefa7f33d8785f960c0810be6870
    commit-message:
      prefix: "security"
      include: "scope"
    ignore:
      # Ignore patch updates for development dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
<<<<<<< HEAD
=======
        dependency-type: "development"
>>>>>>> eff356f9b27adefa7f33d8785f960c0810be6870
        
  # Enable updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    assignees:
      - "Nikhil-Kadapala"
    labels:
      - "ci-cd"
<<<<<<< HEAD
      - "automation"
=======
      - "automation"
>>>>>>> eff356f9b27adefa7f33d8785f960c0810be6870
