name: Deploy Backend

on:
  push:
    branches: [main]
    paths: ['src/api/**', 'src/utils/**']

jobs:
  deploy-to-railway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Railway
        run: |
          npm install -g @railway/cli
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
          railway up

  deploy-to-fly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to Fly.io
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-to-deta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Deta Space
        run: |
          pip install deta
          deta space push
        env:
          DETA_ACCESS_TOKEN: ${{ secrets.DETA_ACCESS_TOKEN }} 